### ISSUE TITLE
Crashing when used with Arboreal Nature

### ISSUE THREAD

**Issue by ChristinWhite** [Globox1997/Nameplate#31]
### Minecraft Version

1.21.x

### Mod Loader Version

 0.16.9

### Mod Version

1.1.5

### Describe the Issue

I'm running into an odd incompatibility with [Arboreal Nature](https://github.com/Alminoris/ArborealNature). Here are the full [Logs](https://gist.github.com/ChristinWhite/bdff0f32551b380a06cfb8e9096db27a), including the crash log and the prism log.

I've also created an [issue](https://github.com/Alminoris/ArborealNature/issues/2) at on Arboreal Nature's repo.

#### Versions

Minecraft: 1.21.1
Prism Loader: 9.1
Fabric Loader: 0.16.9
Java: 17.0.12
macOS: 14.6.1 (23G93)

#### Mods Installed

Arboreal Nature: 0.2.5
Cloth Config v15: 15.0.140
Fabric API: 0.109.0+1.21.1
GeckoLib: 4 4.7
Nameplate: 1.1.5
TerraBlender: 4.1.0.5

Only the two conflicting mods and their dependencies. 

### latest.log

[20:04:37] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.9
[20:04:38] [main/INFO]: Loading 62 mods:
	- arborealnature 0.2.5
	   \-- terraform-wood-api-v1 11.0.0
	- cloth-config 15.0.140
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.109.0+1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-api-lookup-api-v1 1.6.70+b559734419
	   |-- fabric-biome-api-v1 13.0.30+be1ed2d719
	   |-- fabric-block-api-v1 1.0.22+0af3f5a719
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
	   |-- fabric-command-api-v1 1.2.49+f71b366f19
	   |-- fabric-command-api-v2 2.2.28+6ced4dd919
	   |-- fabric-commands-v0 0.2.66+df3654b319
	   |-- fabric-content-registries-v0 8.0.18+b559734419
	   |-- fabric-convention-tags-v1 2.1.2+7f945d5b19
	   |-- fabric-convention-tags-v2 2.9.2+e60e56d419
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
	   |-- fabric-data-attachment-api-v1 1.4.0+da19b51a19
	   |-- fabric-data-generation-api-v1 20.2.23+16c4ae2519
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9919
	   |-- fabric-entity-events-v1 1.7.0+2122d82819
	   |-- fabric-events-interaction-v0 0.7.13+ba9dae0619
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
	   |-- fabric-item-api-v1 11.1.1+d5debaed19
	   |-- fabric-item-group-api-v1 4.1.6+6823f7cd19
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
	   |-- fabric-keybindings-v0 0.2.45+df3654b319
	   |-- fabric-lifecycle-events-v1 2.5.0+01d9a51c19
	   |-- fabric-loot-api-v2 3.0.15+3f89f5a519
	   |-- fabric-loot-api-v3 1.0.3+3f89f5a519
	   |-- fabric-message-api-v1 6.0.13+6573ed8c19
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
	   |-- fabric-networking-api-v1 4.3.0+c7469b2119
	   |-- fabric-object-builder-api-v1 15.2.1+40875a9319
	   |-- fabric-particles-v1 4.0.2+6573ed8c19
	   |-- fabric-recipe-api-v1 5.0.13+6508971219
	   |-- fabric-registry-sync-v0 5.1.3+60c3209b19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-renderer-indigo 1.7.0+c705a49c19
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b319
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   |-- fabric-rendering-v0 1.1.71+df3654b319
	   |-- fabric-rendering-v1 5.0.5+df16efd019
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
	   |-- fabric-resource-loader-v0 1.3.1+5b5275af19
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c719
	   |-- fabric-screen-handler-api-v1 1.3.87+b559734419
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c19
	   |-- fabric-transfer-api-v1 5.4.2+95bead5f19
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- geckolib 4.7
	- java 21
	- minecraft 1.21.1
	- nameplate 1.1.5
	- terrablender 4.1.0.5
	   |-- com_electronwill_night-config_core 3.6.7
	   \-- com_electronwill_night-config_toml 3.6.7
[20:04:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/Users/cwhite/Library/Application%20Support/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[20:04:38] [main/INFO]: Compatibility level set to JAVA_21
[20:04:39] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[20:04:39] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 236 milliseconds
[20:04:43] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[20:04:43] [Render thread/INFO]: Setting user: ChristinWhite
[20:04:44] [Render thread/INFO]: Initialization MOD
[20:04:44] [Render thread/INFO]: Registering sign item with ID: arborealnature:item/hazelnut_sign
[20:04:44] [Render thread/INFO]: Registering sign item with ID: arborealnature:item/hornbeam_sign
[20:04:44] [Render thread/INFO]: Registering sign item with ID: arborealnature:item/hawthorn_sign
[20:04:44] [Render thread/INFO]: Registering sign item with ID: arborealnature:item/quince_sign
[20:04:44] [Render thread/INFO]: Registering sign item with ID: arborealnature:item/plum_sign
[20:04:44] [Render thread/INFO]: Registering sign item with ID: arborealnature:item/mango_sign
[20:04:44] [Render thread/INFO]: Registering sign item with ID: arborealnature:item/fig_sign
[20:04:44] [Render thread/INFO]: Registering sign item with ID: arborealnature:item/viburnum_sign
[20:04:44] [Render thread/INFO]: Registering sign item with ID: arborealnature:item/wild_cherry_sign
[20:04:44] [Render thread/INFO]: Registering sign item with ID: arborealnature:item/white_mulberry_sign
[20:04:44] [Render thread/INFO]: Registered region minecraft:overworld to index 0 for type OVERWORLD
[20:04:44] [Render thread/INFO]: Registered region minecraft:nether to index 0 for type NETHER
[20:04:44] [Render thread/INFO]: Registered region arborealnature:overworld to index 1 for type OVERWORLD
[20:04:44] [Render thread/ERROR]: Mixin apply for mod nameplate failed nameplate.mixins.json:GeoEntityRendererMixin from mod nameplate -> software.bernie.geckolib.renderer.GeoEntityRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on renderMixin could not find any targets matching 'render' in software/bernie/geckolib/renderer/GeoEntityRenderer. Using refmap nameplate-refmap.json [INJECT_PREPARE Applicator Phase -> nameplate.mixins.json:GeoEntityRendererMixin from mod nameplate -> Prepare Injections -> handler$zob000$nameplate$renderMixin(Lnet/minecraft/class_1297;FFLnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse ->  -> Validate Targets]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on renderMixin could not find any targets matching 'render' in software/bernie/geckolib/renderer/GeoEntityRenderer. Using refmap nameplate-refmap.json [INJECT_PREPARE Applicator Phase -> nameplate.mixins.json:GeoEntityRendererMixin from mod nameplate -> Prepare Injections -> handler$zob000$nameplate$renderMixin(Lnet/minecraft/class_1297;FFLnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse ->  -> Validate Targets]
	at org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:369) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:340) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:331) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:48) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.alminoris.arborealnature.ArborealNatureClient.onInitializeClient(ArborealNatureClient.java:50) ~[arborealnature-0.2.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) [fabric-loader-0.16.9.jar:?]
	at knot/net.minecraft.class_310.<init>(class_310.java:477) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:239) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[20:04:44] [Render thread/INFO]: [Indigo] Registering Indigo renderer!

### Do you use any other mods except the required ones?

As listed above.

**Comment by ChristinWhite** [comment]
The developer of Arboreal Nature replied that this is on Nameplate's end and is likely related to #30. If that's confirmed this issue could be closed in favor of it.

**Comment by Globox1997** [comment]
Thanks for the report, fixed with [https://github.com/Globox1997/Nameplate/commit/04a864e4b53377aed5c1355f6701b3ea39f3212c](https://github.com/Globox1997/Nameplate/commit/04a864e4b53377aed5c1355f6701b3ea39f3212c)
